name=DNSLab.IoT
version=0.2.1
author=Akbar Asghari
maintainer=Akbar Asghari
sentence=Simple IoT SDK for ESP32 powered by DNSLab.
paragraph=WiFi and MQTT connectivity with tenant and device based topic namespaces and automatic reconnect.
category=Communication
url=https://github.com/AkbarAsghari/DNSLab.IoT
architectures=esp32
depends=PubSubClient