name=DNSLab
version=0.1.0
author=DNSLab
maintainer=DNSLab
sentence=IoT connectivity library for ESP32 using DNSLab services.
paragraph=DNSLab provides WiFi connectivity, MQTT connection, publish, subscribe, callbacks and automatic reconnection for ESP32.
category=Communication
url=https://github.com/AkbarAsghari/DNSLab.IoT
architectures=esp32
depends=PubSubClient