name=DNSLab.IoT
version=0.3.0
author=Akbar Asghari
maintainer=Akbar Asghari
sentence=DNSLab IoT library for ESP32 and ESP8266.
paragraph=WiFi and MQTT connectivity with Project and Device ID based topic namespaces.
category=Communication
url=https://github.com/AkbarAsghari/DNSLab.IoT
architectures=esp32,esp8266
depends=PubSubClient